### ISSUE TITLE
Call `set_params` for `CoreFellowship`

### ISSUE THREAD

**Issue by bkchr** [polkadot-fellows/runtimes#111]
The `CoreFellowship` was added to the collectives, but the `Params` didn't get initialized. The params configure things like the minimum promotion period etc and also things around the salary. As the salary will be set with https://github.com/polkadot-fellows/RFCs/pull/50, we should take the opportunity and also set the other things like the minimum promotion period.

CC @muharem @joepetrowski

**Comment by joepetrowski** [comment]
Some handy reference when evaluating:

- The Manifesto references time periods in months and years. Of course, these need to be converted to blocks.
    - The Collectives parachain creates 7,200 blocks per day.
    - One year is 365.25 days, or 2,629,800 blocks.
    - One month is 365.25 days / 12, or 219,150 blocks.
- The salary asset, USDT, has 6 decimal places. That is, 1 USDT is `1_000_000` units.

## Values

- Active Salary ([RFC 50](https://github.com/polkadot-fellows/RFCs/blob/main/text/0050-fellowship-salaries.md))
    1. 10,000,000,000 (10,000 USDT)
    2. 20,000,000,000
    3. 80,000,000,000
    4. 120,000,000,000
    5. 160,000,000,000
    6. 200,000,000,000
    7. 200,000,000,000
    8. 200,000,000,000
    9. 200,000,000,000
- Passive Salary (Manifesto _Section 8: Allowances_)
    1. 5,000,000,000 (5,000 USDT)
    2. 10,000,000,000
    3. 40,000,000,000
    4. 60,000,000,000
    5. 80,000,000,000
    6. 100,000,000,000
    7. 100,000,000,000
    8. 100,000,000,000
    9. 100,000,000,000
- Demotion Period (Manifesto _Section 4.3: Continuation_)
    1. 657,450 (3 months)
    2. 657,450
    3. 1,314,900 (6 months)
    4. 1,314,900
    5. 1,314,900
    6. 1,314,900
    7. 0 (infinite)
    8. 0
    9. 0
- Min Promotion Period (Manifesto _Section 5: Rank Summary_)
    1. 0
    2. 2,629,800 (1 year)
    3. 2,629,800
    4. 2,629,800
    5. 2,629,800
    6. 2,629,800
    7. 2,629,800
    8. 13,149,000 (5 years)
    9. 21,038,400 (8 years)
- Offboard Timeout (No reference found)
    - 2,629,800 (1 year)

## Execution Info

- [Encoded call](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fcollectives.api.onfinality.io%2Fpublic-ws#/extrinsics/decode/0x3f0100e40b5402000000000000000000000000c817a804000000000000000000000000205fa012000000000000000000000000b08ef01b00000000000000000000000040be4025000000000000000000000000d0ed902e000000000000000000000000d0ed902e000000000000000000000000d0ed902e000000000000000000000000d0ed902e000000000000000000000000f2052a01000000000000000000000000e40b5402000000000000000000000000902f50090000000000000000000000005847f80d000000000000000000000000205fa012000000000000000000000000e8764817000000000000000000000000e8764817000000000000000000000000e8764817000000000000000000000000e876481700000000000000000000002a080a002a080a005410140054101400541014005410140000000000000000000000000000000000a8202800a8202800a8202800a8202800a8202800a820280054101400201a2000a8202800)
- Call should be executed on the `Fellows` track, as per the [Params Origin](https://github.com/polkadot-fellows/runtimes/blob/v1.0.1/system-parachains/collectives/collectives-polkadot/src/fellowship/mod.rs#L150).

**Comment by andresilva** [comment]
Should we also forcefully `approve` all members from the fellowship-collective? This would make sure that everyone gets inducted into the `fellowship-core` pallet (otherwise they stay in a limbo where promotion/demotion rules aren't applied), and would also make sure that everyone's `last_proof` gets set to the same block (members that have already been inducted into `fellowship-core` have an older `last_proof`).

**Comment by joepetrowski** [comment]
Yeah, that's a good idea. But the origin to retain corresponds to each rank, so we will need to set up a series of referenda to do that. We can schedule them all to enact on the same block.

**Comment by joepetrowski** [comment]
These will do all ranks 1-4 but with unsynchronized enactment. Will change the dispatch time to a shared block number once we are ready to submit.

Accept all rank 1:
 - [Preimage](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-collectives-rpc.polkadot.io#/extrinsics/decode/0x2b00cd0f2804703f037460ac178015d2a7c289bb68ef9fdaac071596ab4425c276a0040aaac705556601003f03dc20836f2e4b88c1858d1e3f918e7358043b4a8abcd2874e74d91d26c52eca2a01003f03caafae0aaa6333fcf4dc193146945fe8e4da74aa6c16d481eef0ca35b8279d7301003f03b4f7f03bebc56ebe96bc52ea5ed3159d45a0ce3a8d7f082983c33ef13327474701003f038465abd5a02f5b42b23e323b73e52416514460b9a3e7c34c94ed8d9f986c3d6e01003f03a66e0f4e1a121cc83fddf3096e8ec8c9e9c85989f276e39e951fb0e4a539876301003f03be415da93670251b3c219aff9d1069ef99d27a453620c20d9b4dde4739caa55d01003f03d851f44a6f0d0d2f3439a51f2f75f66f4ea1a8e6c33c32f9af75fc188afb754601003f03ba3ecfd7483cdcdad1132af7d1e8067816009cbd77fc0bc30eafe8d2218a197101003f031212f18a064433a237a56022beffd0ca0f0baef317b34c7f6f12b19968f1023301003f0346d1b7fd733a68d1c3e53d6bfd7134a5803fe5a4033c2dc9eba2e31dc21c4a6501003f0382bf733f44a840f0a5c1935a002d4e541d81298fad6d1da8124073485983860e01003f0312c039004da5e1e846aae808277098c719cef1f4985aed00161a42ac4f0e002f01003f03d5b89078eed9b9dfec5c7d8413bac0b720bad3bd4078c4d8c89432571319250201003f03585e982d74da4f4290d20a73800cfd705cf59e1f5880aaee5506b5eaaf544f4901003f03c6f57237cd4abfbeed99171495fc784e45a9d5d2814d435de40de00991a73c0601003f03e287c7494655d636a846f5c3347ad2cb3c462a8d46e0832be70fcc0ab54ee62d01003f03145d6c503d0cf97f4c7725ca773741bd02e1760bfb52e021af5a9f2de283012c01003f03307183930b2264c5165f4a210a99520c5f1672b0413d57769fabc19e6866fb2501003f03aa91fc0201f26b713a018669bcd269babf25368eee2493323b1ce0190a178a2701003f038c232c91ef2a9983ba65c4b75bb86fcbae4d909900ea8aa06c3644ca1161db4801003f03f6a7fa830da55dde09b411ff877ed0ee8fd1ceb2009067ab5bc0ffdc54af406501003f0378e4813814891bd48bc745b79254a978833d41fbe0f387df93cd87eae246892601003f03c1df5c7e8ca56037450c58734326ebe34aec8f7d1928322a12164856365fea7301003f03d44824ac8d1edecca67639ca74d208bd2044a10e67c9677e288080191e3fec1301003f036201961514cf5ad87f1c4dd0c392ee28231f805f77975147bf2c33bd671b982201003f031c7529b314d9e87a1c241cfe54312668a3159e1063a0aed9f70d3db1f03f8d1001003f03dca89b135d1a6aee0a498610a70eeaed056727c8a4d220da245842e540a54a740100)
 - [Referendum](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-collectives-rpc.polkadot.io#/extrinsics/decode/0x3d003e0902e2a1b920857466e4c83a4a4fe6ff94d2529b127a95be1e00a10d4a061b56a97ff3030000010a000000)

Accept all rank 2:
- [Preimage](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-collectives-rpc.polkadot.io#/extrinsics/decode/0x2b00cd062804303f03f65f3cade8f68e8f34c6266b0d37e58a754059ca96816e964f98e17c7950507302003f032eba9a39dbfdd5f3cba964355d45e27319f0271023c0353d97dc6df2401b0e3d02003f03eec4bd650a277342ebba0954ac786df2623bd6a9d6d3e69b484482336c549f7902003f03ba3e9b87792bcfcc237fa8181185b8883c77f3e24f45e4a92ab31d07a470352002003f0318d30040a8245c5ff17afc9a8169d7d0771fe7ab4135a64a022c25411734072002003f035a090c88f0438b46b451026597cee760a7bac9d396c9c7b529b68fb78aec5f4302003f0338d442452b078203a37f178906e67650b19128ad687051f1aaca4c0c428b3c0402003f03d8290537d6e31fe1ff165eaa62b63f6f3556dcc720b0d3a6d7eab9627561730402003f036a7d56a801015edae2ebdeafb80bd4191554965942141024a2014ea2a11c847702003f038e06bfc989509d6d625c085209adb405867bdbe4f167ded7e61ec126c683165d02003f039e6eb74b0a6b39de36fb58d1fab20bc2b3fea96023ce5a47941c20480d99f92e02003f03ee3d9d8c48ee88dce78fd7bafe3ce2052900eb465085b9324d4f5da26b145f2b0200)
- [Referendum](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-collectives-rpc.polkadot.io#/extrinsics/decode/0x3d003e09023f129c070b31d173f144b84180aedd113a5a40038fefa332521f06520ce8a80db3010000010a000000)

Accept all rank 3:
- [Preimage](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-collectives-rpc.polkadot.io#/extrinsics/decode/0x2b008d042804203f035068e605e8d0653954d518d7b9025d374b2e374731bbe800cfa6ca89743f705303003f0344a3efb5bfa9023d4ef27b7d31d76f531b4d7772b1679b7fb32b6263ac39100e03003f03ccd87fa65729f7bdaa8305581a7a499aa24c118e83f5714152c0e22617c6fc6303003f03984e16482c99cfad1436111e321a86d87d0fac203bf64538f888e45d793b541303003f03beae5bcad1a8c156291b7ddf46b38b0c61a6aaacebd57b21c75627bfe7f9ab7103003f03c4965f7fe7be8174717a24ffddf684986d122c7e293ddf875cdf9700a07b681203003f03720d807d46b941703ffe0278e8b173dc6738c5af8af812ceffc90c69390bbf1f03003f03e0f0f94962fc0a8c1a0f0527dc8e592c67939c46c903b6016cc0a8515da0044d0300)
- [Referendum](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-collectives-rpc.polkadot.io#/extrinsics/decode/0x3d003e0902c98670e354b3e97171da23a3f22d942a4f036ba458916673ea5d03b1ddf2ab4723010000010a000000)

Accept all rank 4:
- [Preimage](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-collectives-rpc.polkadot.io#/extrinsics/decode/0x2b00bd0128040c3f031c90e3dabd3fd0f6bc648045018f78fcee8fe24122c22d8d2a14e9905073d10f04003f034adf51a47b72795366d52285e329229c836ea7bbfe139dbe8fa0700c4f86fc5604003f038e851ed992228f2268ee8c614fe6075d3800060ae14098e0309413a0a81c44700400)
- [Referendum](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-collectives-rpc.polkadot.io#/extrinsics/decode/0x3d003e090261218cace77aa3fb18438ef4bdcf139e10ac54d7bb8dca2ec049d9e4818feefb6f000000010a000000)

Rank 0 doesn't apply IIUC. Ranks 5 and 6 will need public referenda. Working on those too.

**Comment by joepetrowski** [comment]
Referenda are up:

- Set Params: https://collectives.polkassembly.io/referenda/57
- Accept 1: https://collectives.polkassembly.io/referenda/58
- Accept 2: https://collectives.polkassembly.io/referenda/59
- Accept 3: https://collectives.polkassembly.io/referenda/60
- Accept 4: https://collectives.polkassembly.io/referenda/61
- Accept 5 and 6: https://polkadot.polkassembly.io/referenda/400

**Comment by joepetrowski** [comment]
> Is this really based on collectives parachain blocks as opposed to relay chain blocks? If so, can we fix this (as a followup of course). Using the parachain blocks breaks once we switch to async backing and also prevents core sharing.

Yeah exactly, that was my plan that when we switch to async backing we will need to update anyway and should switch to using the Relay Chain block number as the "clock" to allow core sharing.
