### ISSUE TITLE
 Executing the `Utility::batch_all()` method via `XCM`

### ISSUE THREAD

**Issue by ark930** [polkadot-fellows/runtimes#112]
This RP https://github.com/paritytech/polkadot-sdk/pull/1303 has removed restrictions related to `SafeCallFilter`, allowing actions such as sending XCM messages from Parachain and executing the `Utility::batch_all()` method in the Relaychain. However, we've noticed that `SafeCallFilter` is still retained after the separation of polkadot-runtime and kusama-runtime from the polkadot-sdk into this new project
Was this an oversight in updating? I believe cross-chain invocations of `Utility::batch_all()` are a common practice and should not be restricted.

**Comment by bkchr** [comment]
CC @ggwpez

**Comment by ggwpez** [comment]
Good catch!  
The file was correctly imported at tag [`v1.1.0-rc2`](https://github.com/paritytech/polkadot-sdk/blob/v1.1.0-rc2/polkadot/runtime/polkadot/src/xcm_config.rs) and the Filter was still present there in MR https://github.com/polkadot-fellows/runtimes/pull/28.  
It think there was a period where we had already imported the runtimes but did not yet delete them in the SDK. We need to re-apply these changes.
