### ISSUE TITLE
Switch `construct_runtime!` to use `default` syntax

### ISSUE THREAD

**Issue by bkchr** [polkadot-fellows/runtimes#116]
Currently we are still declaring for every pallet all the parts we want to use for it:
https://github.com/polkadot-fellows/runtimes/blob/d67b905dc8126dee16de042971feedb510e015b7/relay/polkadot/src/lib.rs#L1437-L1437

Instead we can just write:
```
Babe: pallet_babe = 2,
```

There is no real reason to continue using the old syntax of always declaring all parts and it is also more error prone.

**Comment by Aideepakchaudhary** [comment]
@bkchr can i solve this issue?

**Comment by bkchr** [comment]
Yes! thank you
