### ISSUE TITLE
CI: `setup-protoc` hits rate limit

### ISSUE THREAD

**Issue by ggwpez** [polkadot-fellows/runtimes#136]
CI log from [here](https://github.com/polkadot-fellows/runtimes/actions/runs/7410741173/job/20163714022?pr=129):  

```pre
Run arduino/setup-protoc@v1
Error: Error: API rate limit exceeded for 20.55.14.224. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

Retry fixed it.

**Comment by ggwpez** [comment]
cc @alvicsam

**Comment by alvicsam** [comment]
[This commit](https://github.com/polkadot-fellows/runtimes/pull/142/commits/06f5730f5fac98f7204e2c6e48d67e16f8b62dcf) should fix it
