### ISSUE TITLE
`Proxy::Proxies` undecodable storage on Polkadot

### ISSUE THREAD

**Issue by liamaharon** [polkadot-fellows/runtimes#145]
https://github.com/polkadot-fellows/runtimes/actions/runs/7553599023/job/20564716569?pr=137

Looking into it

**Comment by liamaharon** [comment]
There's just a single problematic proxy, introduced here https://polkadot.subscan.io/extrinsic/300532-3 with key `0x1809d78346727a0ef58c0fa03bafa3231d885dcfb277f185f2d8e62a5f290c854d2d16b4be62d0e00e6de68b13b82479fbe988ab9ecb16bad446b67b993cdd9198cd41c7c6259c49`.

My best guess is somehow it's in the old format used prior to https://github.com/paritytech/polkadot-sdk/commit/cf4c744eb3413d9ef4755c34312ba65d5431a899, where the proxy shape was different and somehow the migration did not apply for this key. I'll confirm tomorrow.

**Comment by liamaharon** [comment]
The above hypothesis is correct.

The proxy was not migrated correctly because the `SudoBalances` proxy type was removed from the runtime, rendering the proxy undecodable before it was able to be migrated. I am able to decode the proxy on this branch: https://github.com/liamaharon/runtimes/commit/23c9e98cced5ac9f1c496567deb11501518c0a46

I have opened a PR to simply remove these proxies from storage, since the account they originate from is an old admin acc, which has also become dormant. Could update the pr to instead properly migrate the proxy to the current format if deemed worth the time, but I doubt it..

**Comment by liamaharon** [comment]
Opened referenda to remove instead of via a migration https://polkadot.polkassembly.io/referenda/440

**Comment by liamaharon** [comment]
Referendum passed and confirmed all state decodes.

**Comment by bkontur** [comment]
very cool, also check-migrations for Kusama and Polkadot finally passed:
https://github.com/polkadot-fellows/runtimes/actions/runs/7802169560/job/21278977168?pr=137
https://github.com/polkadot-fellows/runtimes/actions/runs/7802169560/job/21278977603?pr=137
