### ISSUE TITLE
Timeline for runtime proposals

### ISSUE THREAD

**Issue by arrudagates** [polkadot-fellows/runtimes#15]
Is there a timeline for when this repository will officially take over as the source for runtime code? Right now the P[olkadot v1.0.0 release](https://github.com/paritytech/polkadot/releases/tag/v1.0.0) in [paritytech/polkadot](github.com/paritytech/polkadot) invites developers to come to this repo and contribute, however the README states that the runtime code should not be altered at this time, so is there an expected timeline for when we can start proposing changes?

**Comment by bkchr** [comment]
Hey, after this pr is merged https://github.com/polkadot-fellows/runtimes/pull/9

@ggwpez will update his pr to include the latest changes and then the fellowship will vote on this to get it included. So, you can already start creating or against this repo now.

**Comment by ggwpez** [comment]
In short: You can already open merge requests, but we will have to wait with merging them until we completely transitioned. So not sure if its worth it.  
Reason is that the version here should not diverge from the upstream version - otherwise we will get merge conflicts.

**Comment by arrudagates** [comment]
> In short: You can already open merge requests, but we will have to wait with merging them until we completely transitioned. So not sure if its worth it. Reason is that the version here should not diverge from the upstream version - otherwise we will get merge conflicts.

Alright, thanks! Still waiting to get https://github.com/paritytech/polkadot/pull/7490 merged first before I can open the companion PR here anyway, but also wanted to have some clarification for others looking for this information!
