### ISSUE TITLE
remove treasury from Encointer runtime

### ISSUE THREAD

**Issue by brenzi** [polkadot-fellows/runtimes#176]
Since #158, Encointer's treasury will no longer receive fees. While this is more the result of an oversight AFAIU, it may actually make sense to get rid of the treasury on the Encointer system chain altogether.

The new multi-asset treasury is way too complex for just collecting KSM fees. Yet, it is not powerful enough to be used for our plans of [per-community treasuries](https://forum.polkadot.network/t/towards-encointer-self-sustainability/4195)

I suggest to simply remove the treasury pallet and ignore the negligible funds currently in the treasury (<<1KSM)

**Comment by ggwpez** [comment]
How did #158 cause this? Yea if the treasury is not used here then just remove it i guess.  
But why is there only <<1KSM in? Does the chain not collect more fees?

**Comment by brenzi** [comment]
Why only << 1KSM: because almost all extrinsics are paid in community currency (thus purchasing power adjusted). These CC fees are burned. Only registering new communities needs KSM which went to treasury

#158 removed our custom deal-with-fees and replaced it with the standard systemchain.

TBH I haven't tested the behaviour of the new setup in all cases yet

**Comment by ggwpez** [comment]
Okay. Yea then when its not needed maybe also remove it in #177.
