### ISSUE TITLE
Undecodable nomination-pool state after after upgrading to `polkadot-sdk@1.5`

### ISSUE THREAD

**Issue by liamaharon** [polkadot-fellows/runtimes#188]
https://github.com/polkadot-fellows/runtimes/pull/137 had some regression that made Polkadot nomination pool `BondedPool` state unable to completely decode, hence we are seeing failing CI as of that merge commit (e.g. https://github.com/polkadot-fellows/runtimes/actions/runs/7911629580/job/21596088389?pr=184#step:9:1847). Thanks @joepetrowski for raising this.

I'll look into it tomorrow. Probably makes sense in the future to have try-runtime CI checks be `required` so these issues don't sneak by.

**Comment by bkontur** [comment]
This is known issue, please, check [element](https://matrix.to/#/!wVSWmzIkrlPHxGPhqm:parity.io/$1H6PHTJpxQw2_xk-IrW2P4_NPJbII1SkVUGn9v0stT4?via=parity.io&via=web3.foundation&via=matrix.org)

I've prepared hotfix few days ago: https://github.com/paritytech/polkadot-sdk/pull/3305 but we decided just to wait for Polkadot@1.1.2 is enacted on Feb 19: https://polkadot.polkassembly.io/referenda/458

This is the problem with migrations, when they use actual structs from lib.rs. And the problem could happen when older migrations were not yet applied and we need to apply them all.

**Comment by bkontur** [comment]
On Monday, CI should go green, so then we can close this issue

**Comment by liamaharon** [comment]
Confirmed this is fixed, thanks @bkontur
