### ISSUE TITLE
Set `safeXcmVersion` on all relay+SP chains to `3`

### ISSUE THREAD

**Issue by bkontur** [polkadot-fellows/runtimes#190]
We need to change default/safeXcmVersion for all relays and system parachains, because (almost) everywhere there is `2` and we use `SetTopic` feature, which is not supported for `2`, so the [`note_unknown_version` a.k.a version discovery feature](https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/xcm/pallet-xcm/src/lib.rs#L636) is not triggered. This problem occurs for new destinations which are not already added to the [`SupportedVersion`](https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/xcm/pallet-xcm/src/lib.rs#L636).

Unfortunately, this [PR](https://github.com/polkadot-fellows/runtimes/pull/45) with allowed `pallet_xcm::Call::force_default_xcm_version` is not yet upgraded live on Polkadot chains (need to wait for `1_001_00X` is enacted, but governance call can be submitted probably), Kusama's chains should be ready.

- [ ] Kusama https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.dotters.network%2Fkusama#/extrinsics/decode/0x63050103000000
- [ ] Kusama AssetHub https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-asset-hub-rpc.polkadot.io#/extrinsics/decode/0x1f050103000000
- [ ] Kusama BridgeHub https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-bridge-hub-rpc.polkadot.io#/extrinsics/decode/0x1f050103000000

- [ ] Polkadot https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fdot-rpc.stakeworld.io#/extrinsics/decode/0x63050103000000
- [ ] Polkadot AssetHub https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-asset-hub-rpc.polkadot.io#/extrinsics/decode/0x1f050103000000
- [ ] Polkadot BridgeHub https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-bridge-hub-rpc.polkadot.io#/extrinsics/decode/0x1f050103000000
- [ ] Polkadot Collectives https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fdot-rpc.stakeworld.io%2Fcollectives#/extrinsics/decode/0x1f050103000000

**Comment by bkontur** [comment]
@xlc @joepetrowski 
this `force_xcm_version` call should fix that problem with `fellowshipSalary.payout` which Bryan reported
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fdot-rpc.stakeworld.io%2Fcollectives#/extrinsics/decode/0x1f04010100a10f03000000

**Comment by joepetrowski** [comment]
Can you put together everything for a `WhitelistedCaller` referendum?

**Comment by acatangiu** [comment]
I put together the ones for Kusama (setting safe version for AH, BH and Encointer - Kusama Relay is already good):

# Done

Submit the preimage for the Fellowship referendum:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.dwellir.com#/extrinsics/decode/0x2000882c00599c1e250cd67d894136db255afc87fcdd9c29818d4af159efe24374036c3469

Submit the preimage for the public referendum:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.dwellir.com#/extrinsics/decode/0x200071012c0318040c630003000100a10f03082f000006020208af2f01101c1f050103000000630003000100a90f03082f000006020208af2f01101c1f050103000000630003000100a50f03082f000006020208af2f01101c1f050103000000

Open a public referendum to dispatch the call:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.dwellir.com#/extrinsics/decode/0x15002b0d02b19d05907b4955a42e92c45e7cc490da8824bf9696deab5bce2c2718e87bd7145c000000010a000000

# Needs some registered member of Kusama fellowship (I'm not) to do this

Open a Fellowship referendum to whitelist the call:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.dwellir.com#/extrinsics/decode/0x17002b0f021d6c9b45436beaa2787b53611d7d0a09583c5102fb7e13e44ef49f745780562f22000000010a000000

**Comment by bkchr** [comment]
https://kusama.polkassembly.io/referenda/348 whitelisting call.

**Comment by bkontur** [comment]
I put together the ones for Polkadot (setting safe version for AH, BH and Collectives - Polkadot Relay is already good):

## Done
Submit the preimage for the Fellowship referendum:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-collectives-rpc.polkadot.io#/extrinsics/decode/0x2b00d41f0003010003082f0000060342d4336c216f88170040d555be8405ae0ba4a8c0d5cf910cf719a764644e91d0c8f37bf1e87c64c7c8

https://collectives.statescan.io/#/extrinsics/3201877-2

## Needs some with "permissions" and/or enough free balance

Open a Fellowship referendum to whitelist the call:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-collectives-rpc.polkadot.io#/extrinsics/decode/0x3d003e0202953d2a661349cbbf2f7f14af56bad37393a54d1878b593fc4ee9e893bd7eb1ba35000000010a000000

Submit the preimage for the public referendum:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-rpc.dwellir.com#/extrinsics/decode/0x0a00710117031a040c630003000100a10f03082f000006020208af2f01101c1f050103000000630003000100a50f03082f000006020208af2f01101c1f050103000000630003000100a90f03082f000006020208af2f01101c1f050103000000

Open a public referendum to dispatch the call:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-rpc.dwellir.com#/extrinsics/decode/0x1500160d0206597ec60f70946fd70ff4801290ddea6452c69f401c267360c5833c948de09f5c000000000a000000

**Comment by acatangiu** [comment]
Ok, everything done now. Last piece: https://collectives.polkassembly.io/referenda/77

**Comment by acatangiu** [comment]
@bkontur you can close this issue
