### ISSUE TITLE
[CI] Add pipeline for checking benchmarks

### ISSUE THREAD

**Issue by bkontur** [polkadot-fellows/runtimes#197]
The `polkadot-sdk` repository has a [**short-benchmarks** pipeline](https://github.com/paritytech/polkadot-sdk/blob/master/.gitlab/pipeline/short-benchmarks.yml) that helps verify the correctness of benchmarks.

Continuation of: https://github.com/polkadot-fellows/runtimes/issues/50
Depends on: https://github.com/paritytech/polkadot-sdk/issues/3045

**Comment by bkontur** [comment]
@bkchr @Bullrich why a PR merge does not close issues? E.g. in this linked [PR](https://github.com/polkadot-fellows/runtimes/pull/379), I added:
![image](https://github.com/user-attachments/assets/e776decc-027c-4984-a6d1-bc7aa866f893)

And we can see that it is linked:
![image](https://github.com/user-attachments/assets/3ac0174b-03fd-4b2f-81a7-e57f7fba36d3)


Also I encountered the same situation with another [PR](https://github.com/polkadot-fellows/runtimes/pull/397), I had to close linked issue manually.

I [read](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#about-linked-issues-and-pull-requests) it has something to do with a default branch setting. Or is it intentional?

**Comment by Bullrich** [comment]
I had the same problem as you. 

Are you a member of the org?

I have a theory that, when you create a PR linked to an issue, if you are not a org member GitHub will not close the issue (for security reasons?)

**Comment by bkchr** [comment]
I would bet this is some kind of permission issue, because the pr was merged by the bot?
