### ISSUE TITLE
:open_umbrella: Migrate the Polkadot and Kusama runtimes

### ISSUE THREAD

**Issue by ggwpez** [polkadot-fellows/runtimes#2]
Some high-level tasks to complete the migration of the Polkadot and Kusama runtimes into this repo:

- [x] Copy the code from the Polkadot repo https://github.com/polkadot-fellows/runtimes/pull/1
- [x] Add a basic GitHub actions CI like to check that everything compiles.
- [x] ~~Maybe create a Rust toolchain file to fix the Rust version.~~
- [x] Think about how to use the runtimes downstream in the Polkadot repo; crates, copy&paste, git-subtree/module, etc. (Answer: No integration testing from the Monorepo - we have to adhere to semver)

What else? Please edit the issue directly.

**Comment by joepetrowski** [comment]
- [ ] Migrate System Parachain runtimes from Cumulus

**Comment by the-right-joyce** [comment]
- [ ] Release notes templates

**Comment by shawntabrizi** [comment]
Are these points up to date?

**Comment by ggwpez** [comment]
I updated it. The basic version of this is done, the follow-up sync is here https://github.com/polkadot-fellows/runtimes/pull/14
