### ISSUE TITLE
 BUG: XCM transfer of all funds fails and traps assets

### ISSUE THREAD

**Issue by acatangiu** [polkadot-fellows/runtimes#210]
The issue is still not resolved and after Polkadot runtime update users are now loosing assets on Polkadot. Could you reopen? It seems to be issue with when they send XCM transfer that also dusts their account.

Example of Polkadot transaction where user lost his DOT in transfer from AssetHubPolkadot->Polkadot 
https://assethub-polkadot.subscan.io/extrinsic/0xe844257b68019176f815104f845c6e18efa2d85d858c95eebc2077a28fac39c4

This deeply affects experience with Polkadot for users using dApps which damages dApps name.

Edit: There is not even need for account to dust in order for asset transfer to fail. If we sent amount that leaves us exactly with minimum deposit it still fails: https://assethub-polkadot.subscan.io/extrinsic/5766838-2

Edit2: For the context other lower amount transfers work just fine.

_Originally posted by @dudo50 in https://github.com/paritytech/polkadot-sdk/issues/3050#issuecomment-1971375971_

**Comment by acatangiu** [comment]
Root cause is `pallet-xcm` extrinsic failure without rolling back side-effects.

The transfer fails because not enough funds are left in the account to pay for delivery fees, but transfer is partially executed leaving assets trapped.

The unintended side-effects of failed pallet-xcm extrinsic were fixed in https://github.com/paritytech/polkadot-sdk/pull/2405 released in polkadot sdk v1.5.0 which hasn't yet landed in runtimes.

There is also upcoming claim_assets() extrinsic for easy recovery of trapped assets: https://github.com/paritytech/polkadot-sdk/pull/3403

Both the fix and the helper extrinsic will be part of the next runtime upgrade https://github.com/polkadot-fellows/runtimes/issues/140

**Comment by acatangiu** [comment]
Also write some regression tests for above. Run them in this repo CI.

**Comment by thanghang8893** [comment]
I am also experiencing this situation. Looking forward to your earliest update

**Comment by acatangiu** [comment]
New Kusama and Polkadot relay and system chains runtimes were released: https://github.com/polkadot-fellows/runtimes/releases/tag/v1.2.0

This issue will be fixed when they are upgraded on-chain.

**Comment by bxy4543** [comment]
> I am also experiencing this situation. Looking forward to your earliest update

https://polkadot.subscan.io/extrinsic/19605609-3?event=19605609-55
Me too, how do I know when it was upgraded ?

**Comment by acatangiu** [comment]
> > I am also experiencing this situation. Looking forward to your earliest update
> 
> https://polkadot.subscan.io/extrinsic/19605609-3?event=19605609-55 Me too, how do I know when it was upgraded ?

Upgrade is being voted on in OpenGov - when it goes from `Deciding` to `Executed`, the upgrade has happened.

Since the fix has been released, and on-chain upgrade is under way, I am closing the issue.
Please re-open if issues persist after the 1.2.0 upgrade.
