### ISSUE TITLE
Fellowship salary payment over XCM failed

### ISSUE THREAD

**Issue by ggwpez** [polkadot-fellows/runtimes#213]
Tried out `FellowshipSalary::payout` locally in chopsticks and it errors in XCM router validation.  
[This line](https://github.com/paritytech/polkadot-sdk/blob/89fdefcc61d119e1712e8be89318d25f4266243f/cumulus/pallets/xcmp-queue/src/lib.rs#L917) in particular. Code deployed on collectives-polkadot should be `89fdefcc61d119` according to Cargo VCS lockfile.

The called `wrap_version` is getting a `None` from the [`get_version_for`](https://github.com/paritytech/polkadot-sdk/blob/89fdefcc61d119e1712e8be89318d25f4266243f/polkadot/xcm/pallet-xcm/src/lib.rs#L2594) with `dest` arg of `{ parents: 1 }`, which seems to cascade into the error return.

Minimized backtrace:  
```pre
cumulus_pallet_xcmp_queue::<impl staging_xcm::v3::traits::SendXcm for cumulus_pallet_xcmp_queue::pallet::Pallet<T>>::validate (cumulus-pallet-xcmp-queue-0.7.0/src/lib.rs:917)
<(TupleElement0,TupleElement1) as staging_xcm::v3::traits::SendXcm>::validate (staging-xcm-7.0.0/src/v3/traits.rs:542)
<staging_xcm_builder::routing::WithUniqueTopic<Inner> as staging_xcm::v3::traits::SendXcm>::validate (staging-xcm-builder-7.0.3/src/routing.rs:52)
<staging_xcm_builder::pay::PayOverXcm<Interior,Router,Querier,Timeout,Beneficiary,AssetKind,AssetKindToLocatableAsset,BeneficiaryRefToLocation> as frame_support::traits::tokens::pay::Pay>::pay (staging-xcm-builder-7.0.3/src/pay.rs:128)
pallet_salary::pallet::Pallet<T,I>::do_payout (pallet-salary-13.0.0/src/lib.rs:438)
pallet_salary::pallet::Pallet<T,I>::payout::{{closure}} (pallet-salary-13.0.0/src/lib.rs:316)
pallet_salary::pallet::Pallet<T,I>::payout (pallet-salary-13.0.0/src/lib.rs:88)
```

**Comment by bkontur** [comment]
I think when this referenda are executed, it should work: https://github.com/polkadot-fellows/runtimes/issues/190

**Comment by bkontur** [comment]
This issue is exactly the same problem: https://github.com/polkadot-fellows/runtimes/issues/190#issuecomment-1947959182

**Comment by bkchr** [comment]
So we can close this?

**Comment by ggwpez** [comment]
Okay will re-open if that did not fix it.
