### ISSUE TITLE
Zombienet: KusamaAssetHub and KusamaBridgeHub are not producing blocks

### ISSUE THREAD

**Issue by serban300** [polkadot-fellows/runtimes#216]
KusamaAssetHub and KusamaBridgeHub are not producing blocks when started in zombienet

Using a `git blame` like approach, I reached this commit as the one who introduced the issue: https://github.com/polkadot-fellows/runtimes/commit/59172d5fb8feea2646490618bead3b2b4fb06220

The zombienet test that I'm using: https://github.com/polkadot-fellows/runtimes/blob/acf1797c84cc14935ccfd8d34043ef5e20a3de08/integration-tests/bridges/environments/polkadot-kusama/bridge_hub_kusama_local_network.toml

**Comment by bkontur** [comment]
I don't see anything suspicious e.g. for AssetHubKusama [lib.rs](https://github.com/polkadot-fellows/runtimes/commit/59172d5fb8feea2646490618bead3b2b4fb06220#diff-80668ff8e793b64f36a9a3ec512df5cbca4ad448c157a5d81abda1b15f35f1da) and also for chain-spec-generator there is just encointer-related [change](https://github.com/polkadot-fellows/runtimes/commit/59172d5fb8feea2646490618bead3b2b4fb06220#diff-7a4c15e83e4faeffcd759ccc4f2d9d874386bc0103cb898823db093c1ff5c05e).

just a blind guess, try add more collators (3-4)?

**Comment by bkontur** [comment]
Relay chain produces blocks? I don't know, isn't there anything in the logs?

**Comment by serban300** [comment]
Yes, relay chain produces blocks. I don't see anything worth mentioning in the logs

**Comment by bkontur** [comment]
so I would guess that it could be related to the coretime stuff maybe:
https://github.com/polkadot-fellows/runtimes/commit/59172d5fb8feea2646490618bead3b2b4fb06220#diff-efa4caeb17487ecb13d8f5eb7863c3241d84afa2e73fbf25909a2ca89df0f362

because this was introduced in that commit just for Kusama, so maybe some coretime magic should happen?
 @seadanda @eskimor any ideas?

**Comment by serban300** [comment]
Yes, it works if I undo the `coretime`-related changes

@seadanda @eskimor can you PTAL ?

**Comment by eskimor** [comment]
Can we make these Zombienet tests part of the CI?

**Comment by serban300** [comment]
@eskimor I don't know. Personally I would totally support this. But I think we should open a separate discussion for this, and maybe include the CI team. For the moment I see there is no zombienet test in this repo and I think the entire infrastructure that is needed for this is missing (building and pushing docker images for example). I don't know if it's by design or if it just wasn't prioritized.

But as a first step I think it would bring value to include the bridge zombienet test as it is and run it manually. And add it in the CI later depending on the separate discussion.

**Comment by eskimor** [comment]
Done: https://github.com/polkadot-fellows/runtimes/issues/226

**Comment by serban300** [comment]
Closed by https://github.com/polkadot-fellows/runtimes/pull/221
