### ISSUE TITLE
Replace Snowbridge test helper methods once polkadot-sdk 1.8.0 has been released

### ISSUE THREAD

**Issue by claravanstaden** [polkadot-fellows/runtimes#234]
Helper methods copied from the polkadot-sdk should removed with the release and update of the polkadot-sdk into the runtimes repo:

- [Bridge Hub Polkadot runtime tests](https://github.com/polkadot-fellows/runtimes/blob/c4c2995ba409ea739c6219994cb343be5bb5418d/system-parachains/bridge-hubs/bridge-hub-polkadot/tests/snowbridge.rs#L246)
- [Bridge Hub Kusama runtime tests](https://github.com/polkadot-fellows/runtimes/blob/c4c2995ba409ea739c6219994cb343be5bb5418d/system-parachains/bridge-hubs/bridge-hub-kusama/tests/snowbridge.rs#L246)

**Comment by bkontur** [comment]
@claravanstaden it looks like this was fixed here: https://github.com/polkadot-fellows/runtimes/pull/326, right?
can we close this now?

**Comment by claravanstaden** [comment]
@bkontur yeah definitely, closing.
