### ISSUE TITLE
`im-online` session keys migration will not run on Kusama

### ISSUE THREAD

**Issue by s0me0ne-unkn0wn** [polkadot-fellows/runtimes#262]
We have a Kusama runtime upgrade to 1.1.3 on track that will be enacted soon: https://kusama.subsquare.io/referenda/359

That will prevent the execution of the session keys migration in 1.2.0 release: https://github.com/polkadot-fellows/runtimes/blob/2dd830a4e30538836198a4d4eaf68da686a0ef3e/relay/kusama/src/lib.rs#L1863

CC @bkchr

**Comment by bkchr** [comment]
Good find. Can you please make a pr to fix this? Then we need to revert the release once more 🙈

**Comment by s0me0ne-unkn0wn** [comment]
> Can you please make a pr to fix this?

Sure. The question is, do I need to fix it for Polkadot as well? I'm not sure if the Polkadot upgrade pipeline strictly follows Kusama's one. Like, if we have 1.1.2 -> 1.1.3 -> 1.2.0 on Kusama, is it exactly the same for Polkadot? (I mean in the best-case scenario when OpenGov approves those changes)

**Comment by bkchr** [comment]
The upgrade will also be applied for polkadot https://polkadot.polkassembly.io/referenda/581
