### ISSUE TITLE
Whitelist preimage for Snowbridge initialization

### ISSUE THREAD

**Issue by vgeddes** [polkadot-fellows/runtimes#274]
For the BridgeHub<->Ethereum bridge to operate, we need to perform a few initialization routines, that are all baked into a single batched preimage.

## Fellowship referendum

Since I am not currently a fellowship member, I would like to request that the fellowship initiate this referendum on my behalf:

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-collectives-rpc.polkadot.io#/extrinsics/decode/0x3d003e0202d10f283251f659dcc2605aa5a256163e97e114726ff448364a4aa3a9875344f435000000010a000000

A preimage has already been created on the collectives chain using this call:

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-collectives-rpc.polkadot.io#/extrinsics/decode/0x2b00d41f0003010003082f0000060342090a75216f881700ea27d4347656f87e303402cfc98ce2f492b4d0d4751dcd51fca0bdcd213a73f2

The full initialization preimage can be viewed at: https://polkadot.polkassembly.io/referenda/680

# Details

## AssetHub

Enable AssetHub->BridgeHub->Ethereum bridging operations by setting the following runtime storage field:

[BridgeHubEthereumBaseFee](https://github.com/polkadot-fellows/runtimes/blob/31ba26287ec752574244f0d690167f7ae8430c8b/system-parachains/asset-hubs/asset-hub-polkadot/src/xcm_config.rs#L805): 11.4565682000 DOT

### Set address for Snowbridge Gateway contract

The [gateway](https://etherscan.io/address/0x27ca963C279c93801941e1eB8799c23f407d68e7) is the bridging endpoint on Ethereum

[EthereumGatewayAddress](https://github.com/polkadot-fellows/runtimes/blob/31ba26287ec752574244f0d690167f7ae8430c8b/system-parachains/bridge-hubs/bridge-hub-polkadot/src/bridge_to_ethereum_config.rs#L45): [0x27ca963C279c93801941e1eB8799c23f407d68e7](https://etherscan.io/address/0x27ca963C279c93801941e1eB8799c23f407d68e7)

**NOTE**: The deployment of the Gateway is being performed over two stages, to reduce costs and eliminate potential for breakage which could take months to fix.

Initially, a Gateway _proxy_ contract has been deployed, which delegates all behavior to a bare [Shell](https://github.com/Snowfork/snowbridge/blob/main/contracts/src/Shell.sol) contract. This shell contract has no capability other than being upgraded by a trusted operator (which is me).

Finally, we will upgrade the shell to the full trustless and decentralized [implementation contract](https://github.com/Snowfork/snowbridge/blob/main/contracts/src/Gateway.sol), that only be upgraded via Polkadot OpenGov through BEEFY consensus. This will occur when we are reasonably certain that
* BEEFY on Polkadot is stable (i.e running for a few weeks)
* The fellowship and public referendums look like they will be approved

This phased deployment also reduces costs for us considerably, while we wait for our bridge to be activated. Since it would cost us roughly $23000 per month in relaying consensus messages to our BEEFY client.

### Set pricing parameters

Bridging fees for user messages (ie token transfers) are currently calculated using static values that can only be updated via governance.

Some background information:
* For the AssetHub->Ethereum path, fees are credited to the sovereign account of AssetHub on BridgeHub
* For the Ethereum->AssetHub path, fees are credited to the sovereign account of AssetHub on Ethereum.

The pricing parameters we have chosen have considerable buffer to ensure that the AssetHub sovereign accounts, when manually rebalanced, will always be positive.

Our team will fund these sovereign accounts for the initial month of operation.

*NOTE:* We are going to be improving the fee model substantially as a priority in upcoming releases. These improvements will include:
* Dynamic tracking of ethereum gas price on BridgeHub by trustlessly consuming the [EIP-1559](https://www.paradigm.xyz/2020/06/analysis-of-eip-1559) `BaseFeePerGas` field in execution chain headers.
* Eliminate static ETH/DOT exchange rate by implementing:
  * For Polkadot->Ethereum transfers, users can pay fees in WETH
  * For Ethereum->Polkadot transfers, users pay using their own pre-funded sovereign accounts on the destination parachain
  * Or alternatively, consume time-weighted moving average of WETH/DOT rate from the AssetHub DEX.
* Automatic rebalancing of sovereign accounts

### Set Gateway operating mode

Enables Ethereum->AssetHub ERC20 token transfers.

### Set initial checkpoint for the Beacon light client

This operation activates our beacon light client and allows it to follow the progress of the beacon chain.

The checkpoint has been derived from this beacon chain slot: https://beaconscan.com/slot/8870560

# Testing

The initialization preimage has been tested in a simulated chopsticks environment that:
* Forked the Polkadot, BridgeHub, and AssetHub chains
* Had the 1.2.0 runtime release applied

The preimage executed successfully, and furthermore:
* I tested that the necessary storage fields were updated to the correct values
* That AssetHub->BridgeHub token transfers executed successfully, such that messages were committed for delivery to Ethereum

# Preimage generation

The initialization preimage was generated using this command implemented by a [governance tool](https://github.com/Snowfork/snowbridge/tree/main/control) we developed:

```shell
$ snowbridge-preimage initialize \
  --exchange-rate-numerator 1 \
  --exchange-rate-denominator 450 \
  --multiplier-numerator 4 \
  --multiplier-denominator 3 \
  --fee-per-gas 60 \
  --local-reward 0.01 \
  --remote-reward 0.00025 \
  --checkpoint initial-checkpoint.json \
  --gateway-address 0x27ca963C279c93801941e1eB8799c23f407d68e7 \
  --gateway-operating-mode normal > preimage.bin
BridgeHub:
  ExchangeRate: 0.0022222222222222222 ETH/DOT
  FeePerGas: 60.000000000 GWEI
  LocalReward: 0.0100000000 DOT [100000000 PLANCK]
  RemoteReward: 0.000250000000000000 ETH [250000000000000 WEI]
AssetHub:
  BaseFee: 11.4565682000 DOT, [114565682000 PLANCK]
Storage key for 'BridgeHubEthereumBaseFee': 0x5fbc5c7ba58845ad1f1a9a7c5bc12fad
Preimage Hash: 0xea27d4347656f87e303402cfc98ce2f492b4d0d4751dcd51fca0bdcd213a73f2
```
# Sequencing

The initialization preimage should only execute after the [1.2.0 runtime upgrade](https://polkadot.polkassembly.io/referenda/648)

# Audits

Oak security will soon (in the next few days), issue an audit report covering the latest changes to our codebase, as well as the runtime configuration.

They have completed two previous audits available at:
https://github.com/oak-security/audit-reports/tree/main/Snowbridge

# Resources

* Snowbridge repository containing Ethereum contracts, offchain relayers, and other assorted tools: https://github.com/Snowfork/snowbridge
* Snowbridge pallets: https://github.com/paritytech/polkadot-sdk/tree/master/bridges/snowbridge
* Documentation Hub: https://docs.snowbridge.network/

**Comment by Gioyik** [comment]
> Oak security will soon (in the next few days), issue an audit report covering the latest changes to our codebase, as well as the runtime configuration.

could be possible to know the scope of the audit? specially which parts are the latest changes and why those were selected instead of a retest of previous audit scope which had findings.

**Comment by vgeddes** [comment]
The whitelisting [referendum](https://collectives.subsquare.io/fellowship/referenda/100) has executed successfully. Thanks for the approving fellowship folks!

Please direct any further comments about the initialization of Snowbridge here: https://polkadot.polkassembly.io/referenda/680
