### ISSUE TITLE
Proposing: v1.2.4 Release

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-fellows/runtimes#288]
Based on the discussion in the last Fellowship call about smaller patch releases and holding off on v1.3.0 for Coretime, I would propose the following:

## v1.2.3 (Coretime only)

- [x] https://github.com/polkadot-fellows/runtimes/pull/286 (needed to onboard People and re-enable Identity functionality on Kusama)

## v1.2.4

- [x] https://github.com/polkadot-fellows/runtimes/pull/285
- [x] https://github.com/paritytech/polkadot-sdk/pull/4398 / https://github.com/polkadot-fellows/runtimes/pull/309
- [x] https://github.com/polkadot-fellows/runtimes/pull/261
- [x] https://github.com/polkadot-fellows/runtimes/pull/280
- [x] https://github.com/polkadot-fellows/runtimes/pull/289
- [x] (tests) https://github.com/polkadot-fellows/runtimes/pull/260
- [x] (tests) https://github.com/polkadot-fellows/runtimes/pull/251
- [x] (maybe?) https://github.com/polkadot-fellows/runtimes/pull/291
- [x] https://github.com/polkadot-fellows/runtimes/pull/310

I think this could be a parachains-only release, although the Ambassador Program might involve modifying the Fellowship Admin track on the Relay Chain.

Note: We actually need to be careful _not_ to upgrade the Kusama Relay Chain until the People Chain is live, because the Identity Reaper (now guarded by Root) will become open, and it needs a parachain to send to.

**Comment by bkchr** [comment]
- [ ] https://github.com/paritytech/polkadot-sdk/pull/4274

**Comment by seadanda** [comment]
- [ ] https://github.com/polkadot-fellows/runtimes/pull/300

Just in case the intention is to include all runtimes in the release. Kusama Coretime should not be bumped without this PR.

**Comment by joepetrowski** [comment]
> Just in case the intention is to include all runtimes in the release. Kusama Coretime should not be bumped without this PR.

Yeah with the `SafeCallFilter` PR and Basti's we will want to bump everything.

**Comment by pandres95** [comment]
@joepetrowski, Maybe #290?

Honestly it's a perfect match for other XCM related PRs, and how it is right now, it's small enough not to require immense amounts of testing (I've done some tests myself of how this might work using Chopsticks).

We can then make the same modification for similar chains in the future.

**Comment by claravanstaden** [comment]
- [ ] https://github.com/polkadot-fellows/runtimes/pull/313

To fix Snowbridge Ethereum consensus updates being rejected and resets the Ethereum client checkpoint.

**Comment by Ank4n** [comment]
Would like to propose following to be added to v1.2.4
- [ ] https://github.com/paritytech/polkadot-sdk/pull/4525 
- [ ] https://github.com/paritytech/polkadot-sdk/pull/4524

**Comment by joepetrowski** [comment]
Get them in before https://github.com/polkadot-fellows/runtimes/pull/317 :)

Otherwise this train is off and they can go in https://github.com/polkadot-fellows/runtimes/issues/316

**Comment by Ank4n** [comment]
PR here: https://github.com/polkadot-fellows/runtimes/pull/318

**Comment by acatangiu** [comment]
@joepetrowski you can close this
