### ISSUE TITLE
Check license of each crate

### ISSUE THREAD

**Issue by ggwpez** [polkadot-fellows/runtimes#29]
We should double-check that the workspace `GPL-3.0-only` is good and then use that for all crates.

**Comment by ggwpez** [comment]
All crates use the same license and it seems like `GPL-3.0-only` is good for now.

**Comment by bkontur** [comment]
@ggwpez can we remove this TODO: https://github.com/polkadot-fellows/runtimes/blob/main/Cargo.toml#L6?
For integration-tests modules we have still `license = "Apache-2.0"`, shouldn't we change that to `license.workspace`?
