### ISSUE TITLE
v1.2.5 Release

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-fellows/runtimes#316]
## v1.2.5

- [x] https://github.com/paritytech/polkadot-sdk/pull/4274 + backports
- [x] https://github.com/polkadot-fellows/runtimes/pull/337
- [x] https://github.com/polkadot-fellows/runtimes/pull/318
- [x] https://github.com/polkadot-fellows/runtimes/pull/312
- [x] https://github.com/polkadot-fellows/runtimes/pull/323
- [x] https://github.com/polkadot-fellows/runtimes/pull/329
- [x] https://github.com/polkadot-fellows/runtimes/pull/338

**Comment by muharem** [comment]
It would be nice to include this 
- [ ] https://github.com/polkadot-fellows/runtimes/pull/332

**Comment by eskimor** [comment]
- [ ] New [broker pallet](https://github.com/paritytech/polkadot-sdk/pull/4521)

**Comment by muharem** [comment]
@joepetrowski it's not clear with the plan with `CheckMetadataHash` extension?

**Comment by joepetrowski** [comment]
> @joepetrowski it's not clear with the plan with `CheckMetadataHash` extension?

We need to bump to the patch releases of these crates: https://github.com/paritytech/polkadot-sdk/issues/4635

**Comment by seadanda** [comment]
> * [ ]  New [broker pallet](https://github.com/paritytech/polkadot-sdk/pull/4521), draft PR: [WIP: Adjust to new Broker pallet. #334](https://github.com/polkadot-fellows/runtimes/pull/334)

The changes in question depend on a breaking change to the broker pallet in v0.13.0.
To get this into the next release we have to either:
1. update a lot (most?) of the dependencies in the repo
2. backport this breaking change to the broker as a 'fix' to broker 0.7 (based on the 1.7 sdk release)
3. use a git version for the broker pointing to an unreleased version of 2

1 would delay the release by a fair bit, 2 is a pretty bad semver violation and then I know that there is a lot of resistance to 3 being in the codebase.

What are people's opinions on which way is least bad?

**Comment by bkchr** [comment]
> 3\. use a git version for the broker pointing to an unreleased version of 2

We need to use a `patch` in the workspace `Cargo.toml` that uses git.

**Comment by acatangiu** [comment]
>> 2. backport this breaking change to the broker as a 'fix' to broker 0.7 (based on the 1.7 sdk release)

> 2 is a pretty bad semver violation

Are there any other users of the broker pallet? Afaik this is pretty new and its usecase is also very specific. It might actually not break anyone.

**Comment by seadanda** [comment]
There were some unrelated changes in the PR which changed the broker which required a migration, and there is already a broker migration from another commit which has not yet run on `coretime-kusama`. To avoid messing up storage versions, I've isolated the relevant changes for the price adapter and backported them in [this PR](https://github.com/paritytech/polkadot-sdk/pull/4656).

I'd like a second pair of eyes on it before using it as it wasn't just a straightforward backport. Can re-target the PR onto another branch as needed, and whether we go for option 2 or 3 this should be sufficient.

**Comment by muharem** [comment]
- [ ] https://github.com/polkadot-fellows/runtimes/pull/339

**Comment by joepetrowski** [comment]
> * [ ]  [Kusama People: Clear judgements #339](https://github.com/polkadot-fellows/runtimes/pull/339)

I think this can probably go into 1.2.6 with the other People stuff. We need to prioritize the Coretime changes for 1.2.5 due to the Kusama timeline.

**Comment by eskimor** [comment]
- [ ] Run benchmarks for broker pallet.

**Comment by joepetrowski** [comment]
> * [ ]  Run benchmarks for broker pallet.

- [ ] https://github.com/polkadot-fellows/runtimes/pull/343
