### ISSUE TITLE
frame_support::traits::tokens::fungible user's funds may stuck

### ISSUE THREAD

**Issue by stepanLav** [polkadot-fellows/runtimes#328]
Description:

After introducing new balance logic - https://github.com/paritytech/polkadot-sdk/issues/1833#issuecomment-1805764506
there is a case, when user's funds may stuck, that happens when user transfer from his account with reserved and lock balances.

Case:
1. Make account with balance - 5 WND
2. Create reserve balance - 3 WND (create 3 pure proxy)
3. Create locked balance 1 WND (bond 1 WND)
4. Transfer 1 WND to any account

*Actual result:*
User can't sign operations in some pallets, it will fall down with error

proxy - https://westend.subscan.io/extrinsic/20967814-2
staking - https://westend.subscan.io/extrinsic/20967935-2
multisig - https://westend.subscan.io/extrinsic/20967870-2

but he still can transfer some assets from his account (submitted operation after all falls above):
https://westend.subscan.io/extrinsic/20967957-2

Example of that account:
https://westend.subscan.io/account/5EWrvLtq8wdpMTaKHMVNf7tarU7dpfU8Bi1QxRmMaZY2cVHf

Pallets where would be great to get support of new fee deduction:
- staking
- multisig
- proxy
- convictionvoting(all related to governance)

**Comment by muharem** [comment]
@stepanLav do I understand it right, the fee payments with new fungibles implementation fixes this? 
if you confirm I can try to get it with the next patch release. Westend Asset Hub fee payments should be already working with fungibles implementation right now.

**Comment by muharem** [comment]
@stepanLav basically in the use case you have described a user that have a free balance cannot pay the fee? do you have many reports from users? Please give a bit more on the impact.

**Comment by stepanLav** [comment]
> @stepanLav basically in the use case you have described a user that have a free balance cannot pay the fee? do you have many reports from users? Please give a bit more on the impact.

I dived deeper and looks like on the Westend Relaychain it does not reproduce anymore, case itself connected to a problem, when different pallets calculate available part of balance in different ways, some use T::Currency, some - T::Fungibles. As a result, where Fungibles are used, we can pay a fee from accounts with `free` < ``max(`reserved`, `frozen`))``, but where Currency is used, I can't.

it is still reproduce on the Kusama network, so on the account with that balance:

```js
{
  nonce: 4
  consumers: 2
  providers: 1
  sufficients: 0
  data: {
    free: 229,809,526,241
    reserved: 668,033,331,300
    frozen: 300,000,000,000
    flags: 170,141,183,460,469,231,731,687,303,715,884,105,728
  }
}
```

I can't do anything, every time I get `ExtrinsicStatus:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low`, In that case I need to top up my account in order to get `free` > `frozen` to bypass fee verification

**Comment by muharem** [comment]
probably exact same issue as described here - https://github.com/paritytech/polkadot-sdk/issues/1833

**Comment by muharem** [comment]
I will try to get it into https://github.com/polkadot-fellows/runtimes/issues/316

**Comment by Juanma0x** [comment]
> @stepanLav basically in the use case you have described a user that have a free balance cannot pay the fee? do you have many reports from users? Please give a bit more on the impact.

Several users have referred similar problems to the Web3 Foundation support team. Some public examples:
- https://github.com/polkadot-js/apps/issues/9988#issuecomment-2066295859
- [Discord thread on Polkadot's server](https://discord.com/channels/722223075629727774/1237160905624780874)
- [Another Discord thread](https://discord.com/channels/722223075629727774/1223472970777755718)

It was my understanding that the issue was fixed with https://github.com/paritytech/polkadot-sdk/pull/2292 in [Polkadot-SDK v1.11.0](https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-v1.11.0), so it'll be fixed in the runtime whenever Polkadot-SDK v.1.11.0 is adopted, but I might be wrong.

**Comment by muharem** [comment]
> > @stepanLav basically in the use case you have described a user that have a free balance cannot pay the fee? do you have many reports from users? Please give a bit more on the impact.
> 
> Several users have referred similar problems to the Web3 Foundation support team. Some public examples:
> 
> * [Transferable balance is incorrect polkadot-js/apps#9988 (comment)](https://github.com/polkadot-js/apps/issues/9988#issuecomment-2066295859)
> * [Discord thread on Polkadot's server](https://discord.com/channels/722223075629727774/1237160905624780874)
> * [Another Discord thread](https://discord.com/channels/722223075629727774/1223472970777755718)
> 
> It was my understanding that the issue was fixed with [paritytech/polkadot-sdk#2292](https://github.com/paritytech/polkadot-sdk/pull/2292) in [Polkadot-SDK v1.11.0](https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-v1.11.0), so it'll be fixed in the runtime whenever Polkadot-SDK v.1.11.0 is adopted, but I might be wrong.

Yes, but I am trying to get it into the next release as a patch with this PR - https://github.com/polkadot-fellows/runtimes/pull/332

**Comment by esh2n** [comment]
@stepanLav 

Two APIs are no longer executable since the timing of this modification to Westend.

Has anything changed when creating transactions?

- TransactionPaymentApi_query_info
- payment_queryFeeDetails

**Comment by muharem** [comment]
which API you mean? TransactionPaymentApi_query_info and payment_queryFeeDetails ? what's the errori?

the issue described by @stepanLav should be solved with 1.2.5, which is ready to be upgraded now for Polkadot and System Chains

**Comment by niso1985** [comment]
@muharem @stepanLav 
I am in the same situation.
And I am experiencing this situation for the first time on mainnet and I have no information at all and I am confused.
I got it to work right away.
What should I do?
cf. https://substrate.stackexchange.com/questions/11668/suddenly-transactionpaymentapi-query-info-is-generating-wasm-errors-at-block-hei

```
curl -H "Content-Type: application/json" -d '{
  "jsonrpc": "2.0",
  "method": "payment_queryInfo",
  "params": ["0x41028400088ec8045cd8e9fbdd7080021030c5bf7240c9ea36a0648ea3bbe07d54de5d4d0100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a50348000402002c50932cfc2b166f444027517b3421ddb59c64162f090197e4ccac19c30c237b0700e40b5402"],
  "id": 1
}' https://rpc.polkadot.io
{"jsonrpc":"2.0","error":{"code":1,"message":"Unable to query dispatch info.","data":"Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed\nWASM backtrace:\nerror while executing at wasm backtrace:\n    0: 0x63a3 - <unknown>!rust_begin_unwind\n    1: 0x2eb7 - <unknown>!core::panicking::panic_fmt::hbb5a6b42001bdfec\n    2: 0x53ea58 - <unknown>!TransactionPaymentApi_query_info"},"id":1}%
```

**Comment by muharem** [comment]
@esh2n @niso1985 There is a new signed extension that should be included in the transaction. Most likely, its absence is the reason you are getting that error.
 https://github.com/polkadot-fellows/runtimes/pull/337

**Comment by muharem** [comment]
@stepanLav the issue should be fixed now

**Comment by niso1985** [comment]
@muharem Thank you. You're a big help.

**Comment by stepanLav** [comment]
@muharem Thank you!
I've checked Kusama and Polkadot and now there is no problem to pay fee in governance\proxy\staking pallets
