### ISSUE TITLE
Add try-runtime migration tests

### ISSUE THREAD

**Issue by liamaharon** [polkadot-fellows/runtimes#33]
Add tests to programatically check there're no try-runtime errors on runtime upgrade for all runtimes in this repo, using the [try-runtime-cli core library](https://paritytech.github.io/try-runtime-cli/try_runtime_core/index.html).

**Comment by kianenigma** [comment]
I would love it if we could finally introduce some kind of a runtime burn-in for runtime as well. 

For example, running `follow-chain --check RoundRobin(1)` for 1024 blocks should yield no `ERROR` logs.

**Comment by bkchr** [comment]
This is also done.

@kianenigma proposal should be put into some new issue in the try runtime repo. @liamaharon can you do this?

**Comment by liamaharon** [comment]
> This is also done.
> 
> @kianenigma proposal should be put into some new issue in the try runtime repo. @liamaharon can you do this?

https://github.com/polkadot-fellows/runtimes/issues/35
