### ISSUE TITLE
Version of `log` is pinned to `0.4.20`

### ISSUE THREAD

**Issue by ggwpez** [polkadot-fellows/runtimes#333]
We can currently not update to newer SDK versions since zombienet-sdk pins the version of log through using [deno_net 0.115](https://crates.io/crates/deno_net/0.115.0/dependencies).

@pepoviola is on this i think.

**Comment by pepoviola** [comment]
Should be solved in the latest version, I will take a look. Thanks for the heads up @ggwpez!

**Comment by pepoviola** [comment]
_Update_: @ggwpez  I just released a new version of zombienet-sdk (v0.2.3) that fix this issue.
Thanks!
