### ISSUE TITLE
Integrate and release ideal staking rate change

### ISSUE THREAD

**Issue by bkchr** [polkadot-fellows/runtimes#36]
https://github.com/polkadot-fellows/runtimes/pull/26

**Comment by gpestana** [comment]
Are there any updates on releasing this adjustment in Polkadot? The crowdloans unlock is coming up (around mid October) and it would be great to have this change in before the unlock.

**Comment by kianenigma** [comment]
I will make a separate release for this today which we can propose to enact on both network independent of the fellowship runtimes. #26 should be merged in any case though.

**Comment by kianenigma** [comment]
https://hackmd.io/ykunWzXYR-Kaz_cM2KNIlg

**Comment by gpestana** [comment]
I reproduced the runtime build https://hackmd.io/_h7H8pYsSvmWkleGCvqUUw, the hashes match.

**Comment by kianenigma** [comment]
https://polkadot.polkassembly.io/referenda/166
