### ISSUE TITLE
Explicit default for testnet `HostConfiguration`

### ISSUE THREAD

**Issue by ggwpez** [polkadot-fellows/runtimes#362]
A `..Default::default()` [here](https://github.com/polkadot-fellows/runtimes/blob/9ec5d841f966674ce6821e90d90883e50cd5691f/chain-spec-generator/src/relay_chain_specs.rs#L77) is hiding newly added fields.  
Maybe someone should take a look if these values are sane and add explicit default so that it fails in the future instead of using 0.

**Comment by dharjeezy** [comment]
For this, are you saying we specify each property and provide them with their default one by one?

**Comment by ggwpez** [comment]
Yea, but i dont know what values are good defaults.

**Comment by ggwpez** [comment]
Done in https://github.com/polkadot-fellows/runtimes/pull/368
