### ISSUE TITLE
PeopleKusama, PeoplePolkadot and Encointer don't have price for parent delivery set up

### ISSUE THREAD

**Issue by acatangiu** [polkadot-fellows/runtimes#388]
`PeopleKusama`, `PeoplePolkadot` and `Encointer` don't have price for parent delivery set up.

They should.

_Originally found by @franciscoaguirre in https://github.com/polkadot-fellows/runtimes/issues/380#issuecomment-2230386290_

**Comment by franciscoaguirre** [comment]
Seems like this was absolutely unintended since the type is created but not used 😅
