### ISSUE TITLE
Check `merge bot` and required pipelines

### ISSUE THREAD

**Issue by bkontur** [polkadot-fellows/runtimes#396]
E.g. this [PR](https://github.com/polkadot-fellows/runtimes/pull/380) was merged but one pipeline `integration-test (bridge-hub-kusama, bridge-hub-kusama-integration-tests)` failed, how is that possible?

![image](https://github.com/user-attachments/assets/5817208b-8123-45fc-89bf-271817d26c8e)

**Comment by bkontur** [comment]
cc: @Bullrich

**Comment by Bullrich** [comment]
The method `continue-on-error: true` seems to be the main offender.

We should remove it in both places:
- https://github.com/polkadot-fellows/runtimes/blob/7723274a2c5cbb10213379271094d5180716ca7d/.github/workflows/test.yml#L48
- https://github.com/polkadot-fellows/runtimes/blob/7723274a2c5cbb10213379271094d5180716ca7d/.github/workflows/test.yml#L100

**Comment by bkontur** [comment]
I removed `continue-on-error: true` here: https://github.com/polkadot-fellows/runtimes/pull/397 and I will also add a fix.

Maybe `fail-fast: false` looks better: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

**Comment by bkontur** [comment]
definitely, `continue-on-error: true` is not good, because tests failed and this pipeline passed :)
![image](https://github.com/user-attachments/assets/b9a0eb8f-248f-4644-ac56-518ce405511d)

**Comment by bkontur** [comment]
@Bullrich I removed `continue-on-error: true` and now that pipeline [`confirmTestPassed`](https://github.com/polkadot-fellows/runtimes/blob/main/.github/workflows/test.yml#L251C3-L251C20) is marked as a skipped:
`Test all features / All tests passed (pull_request) Skipped `

![image](https://github.com/user-attachments/assets/78c5ca8c-90c4-4b9a-8a8d-7ef435e9fe47)


So, is that `confirmTestPassed` marked as a required to block merge in the github configuration?

**Comment by bkchr** [comment]
Marked all the "All ****" as required.

**Comment by bkontur** [comment]
Fixed by https://github.com/polkadot-fellows/runtimes/pull/397
