### ISSUE TITLE
Merge rights

### ISSUE THREAD

**Issue by bkchr** [polkadot-fellows/runtimes#41]
We have support for giving approval rights to fellowship members. Now we need to have merge rights. IMO every fellowship member or the block author should be able to write "bot merge" into a pull request comment. If all CI checks are green, the pull request should be merged to master.

**Comment by bkchr** [comment]
@rzadp maybe you can help?

**Comment by xlc** [comment]
It should be possible to have the GH action automatically perform the merge on the approved event. But it maybe a good idea to require an explicitly merge command to trigger the merge.

**Comment by bkchr** [comment]
> It should be possible to have the GH action automatically perform the merge on the approved event.

Yeah, we could havve used `mergify` for this. However, I don't want to automatically merge when everyone approved, as people may have left some last comments or similar.

**Comment by Bullrich** [comment]
Why not use a auto merge?

We can do something simple as:
- When someone comments `/bot merge` (or your command of preference) it triggers the GitHub action.
- The GitHub action enables [`auto-merge`](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request#enabling-auto-merge) in the PR.
- When all the approvals/checks has passed, it automatically merges it the old fashion way 😃 

I would be happy taking this task if you like my proposal.

**Comment by rzadp** [comment]
>   * When someone comments `/bot merge` (or your command of preference) it triggers the GitHub action.
>   * The GitHub action enables [`auto-merge`](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request#enabling-auto-merge) in the PR.
>   * When all the approvals/checks has passed, it automatically merges it the old fashion way 😃

This sounds great to me.

@Bullrich Just FYI it looks like enabling the auto-merge on a PR is not possible with the Github REST API, but it's possible with the GraphQL API.

**Comment by xlc** [comment]
I guess we will also need to be able to cancel auto merge? But then the permission become a bit unclear.

**Comment by bkchr** [comment]
I would say we give the same people that can do `/bot merge` the rights to `/bot cancel`. If we see that this doesn't work, we can change it in the future? Like only allow to cancel once or whatever. Auto merge should probably also be disabled on any change to the pr.

**Comment by Bullrich** [comment]
> @Bullrich Just FYI it looks like enabling the auto-merge on a PR is not possible with the Github REST API, but it's possible with the GraphQL API.

I looked into it, it **should** work without any problems, unless that the GraphQL API requires weird permissions (let's hope it doesn't).

> I guess we will also need to be able to cancel auto merge? But then the permission become a bit unclear.

@bkchr suggestion of a cancel command sounds good.

> Auto merge should probably also be disabled on any change to the pr.

Would it make sense to enable the following branch protection rule?
![image](https://github.com/polkadot-fellows/runtimes/assets/8524599/5e0cce37-0c2e-46cf-a634-26829f14a921)

I believe that keeping it active is a good idea as, what you need, is not the user wanting to merge the changes, but the changes (including new changes) to be reviewed. It also makes the process more smooth

I.E.: 
- I make a PR changing something in the readme.
- I enable `auto-merge`
- You correct me because of a typo: change `wodr` to `word`.
- I fix the typo.
- You approve
- PR merges.

With the auto disable feature:
- I make a PR changing something in the readme.
- I enable `auto-merge`
- You correct me because of a typo: change `wodr` to `word`.
- I fix the typo.
- `auto-merge` gets disabled.
- You approve
- I enable `auto-merge`
- PR merges.

In other companies where I worked (and even in the Polkadot-SDK repository) I have seen the `auto-merge` enabled between changes, as enabling and disabling it constantly only gives more overhead. Checks and reviews still need to be approved for a merge.

**Comment by Bullrich** [comment]
I have some nice progress.

It is not difficult to achieve 🥳 

![image](https://github.com/polkadot-fellows/runtimes/assets/8524599/993c6ed1-539f-4564-ba0d-d762b00b84f4)

I need to clean up the code, but I'll have a first version ready soon.

https://github.com/paritytech/auto-merge-bot

**Comment by Bullrich** [comment]
The application is in development. Find the related tickets here:
- paritytech/auto-merge-bot#1
- paritytech/auto-merge-bot#2
- paritytech/auto-merge-bot#3
- paritytech/auto-merge-bot#4

**Comment by Bullrich** [comment]
@bkchr a couple of questions to clarify functionality:

> IMO every fellowship member or the block author should be able to write "bot merge" into a pull request comment

I currently set it up to be allowed by users who belong to the org `polkadot-fellows` or the author of the PR (I assume that is what you meant by `block author`).

Should I also add in the list of authorized users the users who are part of the fellows? Or being a member of the org suffices the requirement?

**Comment by mutantcornholio** [comment]
Just to challenge the idea. Maybe allow the author to do GitHub-native automatic merge, just make the fellowship review (via review-bot) the requirement? 

Do we want to have two different fellowship steps, where it could be just one?

**Comment by bkchr** [comment]
> I assume that is what you meant by `block author`

Ohh, "block author" :facepalm: Too much blockchain for me :P Yes, I meant pr author :see_no_evil: 

> who belong to the org `polkadot-fellows` or the author of the PR

Not the users of the `polkadot-fellows` org. Every fellowship member that is registered on chain. Aka use the on chain fellowship list, as we do for approvals. However, for merging every member of the fellowship can issue the command. We just need to have some list to not allow everybody, as they would otherwise troll or whatever.



> Just to challenge the idea. Maybe allow the author to do GitHub-native automatic merge, just make the fellowship review (via review-bot) the requirement?

But then only the pr author can do this. And can we even allow external people to the "polkadot-fellows" org to do this?

**Comment by mutantcornholio** [comment]
> And can we even allow external people to the "polkadot-fellows" org to do this?

For some reason, I was sure that that's the case, but now I've doublechecked the docs, and apparently not...   
Well, that's that then.

**Comment by Bullrich** [comment]
PR has been created: https://github.com/polkadot-fellows/runtimes/pull/55
