### ISSUE TITLE
Actually benchmark `pallet_xcm::execute` for all runtimes

### ISSUE THREAD

**Issue by franciscoaguirre** [polkadot-fellows/runtimes#436]
We removed a filter to [allow arbitrary XCM execution](https://github.com/polkadot-fellows/runtimes/pull/345) in the runtimes, but if you actually try to call `pallet_xcm::execute` you'll get an error saying you exceed max weight.
This is because `pallet_xcm::execute` has max weight.
This was done to disallow it, now we should benchmark it again.

This is the case for most runtimes in the repo.

**Comment by bkontur** [comment]
@franciscoaguirre yes, you're right, exactly, I saw this when I did fresh weights comparision today: https://github.com/polkadot-fellows/runtimes/pull/433 - all are regenerated (just kusama is missing, I will push in few hours)

**Comment by franciscoaguirre** [comment]
My bad, didn't see that PR 🙈
