### ISSUE TITLE
Polkadot: Many failed `PayoutStakers` calls

### ISSUE THREAD

**Issue by ggwpez** [polkadot-fellows/runtimes#498]
Somehow `Staking::PayoutStakers` fails about 1000 times per day on Polkadot:

<img width="1415" alt="Screenshot 2024-11-01 at 14 26 01" src="https://github.com/user-attachments/assets/bb08ca76-4e51-4b14-ba41-8a57483adf0f">

Seems fine on Kusama:

<img width="1411" alt="Screenshot 2024-11-01 at 14 26 21" src="https://github.com/user-attachments/assets/7783ce1d-e695-4c93-bf51-56b7638058cb">

Also visible on [Subscan](https://polkadot.subscan.io/extrinsic?page=1&time_dimension=date&signed=all&module=staking&call=payout_stakers). Does someone know why that is?

**Comment by bkchr** [comment]
I checked some and these errors looked like people sending the same tx multiple times. You can probably look deeper into the error types. Maybe some people are using a broken bot.

**Comment by clangenb** [comment]
I remember that. Some bots took a while to update to the `CheckMetadataHash` signed extension. I am 99% sure, that this was in the above timeframe.
