### ISSUE TITLE
Add support for update benchmarks

### ISSUE THREAD

**Issue by bkontur** [polkadot-fellows/runtimes#50]
## Problem

The `polkadot-sdk` repository has a [**short-benchmarks** pipeline](https://github.com/paritytech/polkadot-sdk/blob/master/.gitlab/pipeline/short-benchmarks.yml) that helps verify the correctness of benchmarks. In `polkadot-fellows`repository, we currently lack a similar pipeline for benchmark verification. Additionally, there is no existing "bench bot" to automatically regenerate weight files for `polkadot-fellows` runtimes. To maintain the integrity of our benchmarks and ensure the accuracy of weight files, we need to address these issues.

## Proposed solution 1 - add pipeline

This pipeline will be responsible for running benchmarks and verifying their correctness on every PR.

## Proposed solution 1 - regeneration

Since there is no existing "bench bot" for automatic regeneration of weight files for runtimes, we can implement a manual process or script.

## Unresolved questions

- [ ] How and where to regenerate weights for this repo? 
- [ ] What `binary` version to use? Benchmark commands are inside `polkadot` or `polkadot-parachain` binary)
- [ ] When to regenerate weight? Manually? On every release? On master?

cc: @ggwpez

**Comment by bkchr** [comment]
> * How and where to regenerate weights for this repo?

Anyone can do this using the standard hardware. It should be documented here prominently what the standard hardware is. Then people also verify that the posted weights are in the same ball park, aka correct.

> * What `binary` version to use? Benchmark commands are inside `polkadot` or `polkadot-parachain` binary)

Use the latest version and add a comment into the pull request about the version to make this process reproducible.

> * When to regenerate weight? Manually? On every release? On master?

Manually. Fellowship doesn't has any infrastructure and depends on contributors to run the benchmarks. The fellowship members approving the pull request are then required to reproduce the weights to ensure that they are correct.

**Comment by xlc** [comment]
We will need a tool to compare the weights. I am not going to review all the numbers and check if all of them are close enough.

**Comment by acatangiu** [comment]
> Manually. Fellowship doesn't has any infrastructure and depends on contributors to run the benchmarks. The fellowship members approving the pull request are then required to reproduce the weights to ensure that they are correct.

Would it be interesting to explore if someone (some-company or some chain-collective) would sponsor some infrastructure for this?
That way weights generation could be automated and the results also trusted without manual rechecking (depending on the level of control & trust over the provided infra).

**Comment by bkchr** [comment]
> We will need a tool to compare the weights. I am not going to review all the numbers and check if all of them are close enough.

@ggwpez already has a tool for this! He can share this. I was also not expecting for you to do this manually :D 



> That way weights generation could be automated and the results also trusted without manual rechecking (depending on the level of control & trust over the provided infra).

This is the same trust level as trusting the guy that opens the PR. But yeah, theoretically it would work. However, this increases then the maintenance burden etc. Even in Parity all this stuff isn't working smoothly all the time. Having just one script that you can run on a machine sounds fine for me right now.

**Comment by xlc** [comment]
most of the devs won’t have access to a standard hardware machine locally so we will also need some guides on setting up one cloud providers

**Comment by bkchr** [comment]
We have already this: https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot

**Comment by shawntabrizi** [comment]
> @ggwpez already has a tool for this! He can share this. I was also not expecting for you to do this manually :D

I believe this is the tool: https://github.com/ggwpez/substrate-weight-compare

**Comment by xlc** [comment]
Nice. Now we just need to have everything documented somewhere.

**Comment by svyatonik** [comment]
@bkontur FWIW I'm using [this branch](https://github.com/NachoPal/runtimes/pull/1) to do benchmarks locally. So something like:
1) `cargo build --release -p chain-spec-generator --features runtime-benchmark` 
2) `./target/release/chain-spec-generator bridge-hub-polkadot-local --raw >bridge-hub-polkadot-local-raw.json`
3) `../polkadot-sdk/target/release/polkadot-parachain-benchmarks benchmark pallet --chain bridge-hub-polkadot-local-raw.json --pallet=palet-bridge-grandpa --extrinsic=` where the `polkadot-parachain-benchmarks` is the `polkadot-parachain` binary, compiled with `--features runtime-benchmark`
