### ISSUE TITLE
Dismiss approval on new changes

### ISSUE THREAD

**Issue by xlc** [polkadot-fellows/runtimes#60]
Do we want to dismiss approval on PR on new changes? Otherwise the PR author can change the PR to something else and merge it.

**Comment by bkchr** [comment]
@Bullrich can you take care of this?

**Comment by Bullrich** [comment]
Hi @bkchr, this is a check that can be enabled at the branch protection settings:

![image](https://github.com/polkadot-fellows/runtimes/assets/8524599/facdb219-37e3-4c0e-87f1-01dd61aa8a17)

**Comment by bkchr** [comment]
Ahh nice! Then I will enable this. Ty!

**Comment by bkchr** [comment]
Done

**Comment by bkchr** [comment]
Okay, that is actually not working. This only removes approvals from people who approval rights in the repo. Thus, anyone outside approval isn't removed.

**Comment by Bullrich** [comment]
> Okay, that is actually not working. This only removes approvals from people who approval rights in the repo. Thus, anyone outside approval isn't removed.

I did not know that. I will make a small action to handle this then 🙂

**Comment by Bullrich** [comment]
@bkchr find PR with the requested feature: 
- https://github.com/polkadot-fellows/runtimes/pull/76

**Comment by mordamax** [comment]
@bkchr this can be closed already?
